site_name: Pygen Docs
docs_dir: docs
use_directory_urls: false
theme:
    name: gitbook
nav:
    - Home: index.md

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
